from langgraph.graph import StateGraph, START, END
from langchain_deepseek import ChatDeepSeek
from typing import TypedDict
from dotenv import load_dotenv
import os

# --- State ---
# This defines what data flows through the agent graph.
# For now, a question goes in, an answer comes out.
class AgentState(TypedDict):
    question: str
    answer: str

load_dotenv()  # Load environment variables from .env file
deepseek_api_key = os.getenv("DEEPSEEK_API_KEY")  # Get the API key from environment variables


# --- LLM ---
# DeepSeek Chat is the model powering the agent's thinking.
llm = ChatDeepSeek(model="deepseek-flash", api_key=deepseek_api_key)

def think(state: AgentState) -> AgentState:
    """
    This function takes in the current state of the agent, which includes a question,
    and returns a new state that includes the answer generated by the LLM.
    """
    # Use the LLM to generate an answer based on the question
    answer = llm.invoke(state["question"])

    # Return a new state with the answer included
    return {"answer": answer.content}

# --- Graph ---
# Build the graph: START -> think -> END
graph = StateGraph(AgentState)
graph.add_node("think", think)
graph.add_edge(START, "think")
graph.add_edge("think", END)

# Compile the graph into an agent that can be run
agent = graph.compile()

# --- Run the agent ---
if __name__ == "__main__":
    # Example question to ask the agent
    Q = "What is today's date?"
    result = agent.invoke({"question": Q})
    print(f"Q: {Q}")
    print(f"A: {result['answer']}")
    print()

    Q = "What is the difference between an AI agent and a chatbot? Give three key differences."
    result = agent.invoke({
        'question': Q
    })
    print(f"Q: {Q}")
    print(f"A: {result['answer']}")
